### ISSUE TITLE
Why the new names for modules/Slug ?

### ISSUE THREAD

**Issue by Petervos2018** [hdavid/VCVRack-Holon.ist#9]
`"plugin": "HolonicSystemsFree",
      "version": "1.0.0",
      "model": "SwissCheeseKnife"`

`"plugin": "HolonicSystems-Free",
      "version": "0.6.6",
      "model": "HolonicSystems-SwissCheeseKnife"`

You know that this makes it very hard to load old projects into VCVRack 1.00 ?

Greetings Peter

**Comment by hdavid** [comment]
ho damn. i did not realised this. sorry. will fix it shortly.

**Comment by Petervos2018** [comment]
Good to hear,

You are also the only one with 2 mentions in the Plug-in Library for 1.00 and 0.66.
This has probably also to do with the name change ?
As you can see here :
https://vcvrack.com/plugins.html#holo

Greetings Peter

**Comment by hdavid** [comment]
not sure why they appear twice to be fair. it's andrew and his team that manage that, i just submitted the code. but i will check with them.

**Comment by hdavid** [comment]
Fixed in last commit on v1 branch : 9e0146ea0188edcce68fef56ca01b11d64a157ff
will submit to VCV Rack team. Thanks for reporting this!

Unfortunately two of the plugins had a space in the slug (Dumbwaiter and LazySusan) and this is not accepted in 1.0. Thanks to the way VCV1.0 works it will clean the old plugin slugs in files and load fine the old files. But onces saved with 1.0, if opening with 0.6.x the two mentioned plugin will not be loaded.

Cheers,
Henri

**Comment by Petervos2018** [comment]
Well done they all load in 1.00 ! 
Maybe now you should check the links on the Plugin Library page because some of them go to a 404 page.
namely this one : https://holonic.systems/vcv/

Thank you very much.

Peter.

**Comment by hdavid** [comment]
Ah damn ! It should be http://holon.ist/vcv/ 
Thank you, I will fix it in next release !
